SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[Table_2]'
GO
IF OBJECT_ID(N'[dbo].[Table_2]', 'U') IS NOT NULL
DROP TABLE [dbo].[Table_2]
GO
PRINT N'Dropping [dbo].[Table_1]'
GO
IF OBJECT_ID(N'[dbo].[Table_1]', 'U') IS NOT NULL
DROP TABLE [dbo].[Table_1]
GO

