SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating schemas'
GO
IF SCHEMA_ID(N'$(schemas)') IS NULL
EXEC sp_executesql N'CREATE SCHEMA [$(schemas)]
AUTHORIZATION [dbo]'
GO
PRINT N'Altering [dbo].[Table_1]'
GO
IF (NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'a' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] ADD[a] [nchar] (10) NULL
IF (NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'b' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] ADD[b] [nchar] (10) NULL
GO
IF (EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'campo1' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] DROP COLUMN [campo1]
IF (EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'campo2' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] DROP COLUMN [campo2]
IF (EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'campo3' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] DROP COLUMN [campo3]
GO
PRINT N'Altering [dbo].[Table_2]'
GO
IF (EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_2' AND COLUMN_NAME = N'melvin' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_2] DROP COLUMN [melvin]
GO

