SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[Table_1]'
GO
IF (NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'campo1' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] ADD[campo1] [nchar] (10) NULL
IF (NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'campo2' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] ADD[campo2] [nchar] (10) NULL
IF (NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'campo3' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] ADD[campo3] [nchar] (10) NULL
GO
IF (EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'a' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] DROP COLUMN [a]
IF (EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_1' AND COLUMN_NAME = N'b' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_1] DROP COLUMN [b]
GO
PRINT N'Altering [dbo].[Table_2]'
GO
IF (NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Table_2' AND COLUMN_NAME = N'melvin' COLLATE Latin1_General_CS_AS))
ALTER TABLE [dbo].[Table_2] ADD[melvin] [nchar] (10) NULL
GO
PRINT N'Dropping schemas'
GO
IF SCHEMA_ID(N'$(schemas)') IS NOT NULL
DROP SCHEMA [$(schemas)]
GO

